### ISSUE TITLE
not able to give it a try

### ISSUE THREAD

**Issue by VictorBaudot** [NathanCheshire/query-string-modals#1]
I use Vite and receive the following error as soon as I try to import it:

> [vite] Internal server error: Failed to resolve entry for package "query-string-modals". The package may have incorrect main/module/exports specified in its package.json.

**Comment by NathanCheshire** [comment]
@VictorBaudot working on a deployment issue currently. I'll post here when I'm able to successfully pull it myself again.

**Comment by NathanCheshire** [comment]
@VictorBaudot I am able to pull in version `0.0.36` and use in my own project.
